directories:
  output: electron-build
  buildResources: build
appId: com.sanguogame.app
productName: 三国纵横消战天下
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target: nsis
electronVersion: 41.2.0
